stash

diff --git a/packaging/assets/init/rethinkdb b/packaging/assets/init/rethinkdb
--- a/packaging/assets/init/rethinkdb
+++ b/packaging/assets/init/rethinkdb
@@ -1,26 +1,100 @@
 #!/bin/sh
-# Copyright 2014 RethinkDB.
+# Copyright 2015 RethinkDB.
 # Portions from Frank Trampe and Novell used with permission.
-
-# This file targets Ubuntu and is not in line with the Linux specification. Move runlevel 2 from Default-Start to Default-Stop for compliance.
 
 ### BEGIN INIT INFO
 # Provides:          rethinkdb
-# Required-Start: $remote_fs
-# Required-Stop: $remote_fs
+# Required-Start:    $remote_fs
+# Required-Stop:     $remote_fs
 # Default-Start:     2 3 4 5
 # Default-Stop:      0 1 6
-# Short-Description: This starts a set of rethinkdb server instances.
-# Description:       This looks in /etc/rethinkdb/instances.d for rethinkdb config files and launches, stops, or examines each instance described there.
+# Short-Description: This starts a RethinkDB server
+# Description:       Launches the RethinkDB server configured in /etc/rethinkdb/
 ### END INIT INFO
 
 set -e -u
 umask 022
 
-itask="${1:-}"
+rethinkdb_bin=/usr/bin/rethinkdb ;
+rethinkdb_conf_dir=/etc/rethinkdb ;
 
-rtdbbin=/usr/bin/rethinkdb ;
-rtdbconfigdir=/etc/rethinkdb ;
+# is_running <pid>
+# test if the process exists
+is_running () {
+    ps -p "$1" > /dev/null
+}
+
+usage_fail () {
+    echo "Usage: /etc/init.d/rethinkdb [start|stop|restart|force-restart|status|upgrade-config]"
+    exit 1
+}
+
+if [ ! -d "$rethinkdb_conf_dir/instances.d" ]; then # Post-2.1 config
+
+rethinkdb_pid_file=/var/run/rethinkdb.pid
+rethinkdb_log_file=/var/log/rethinkdb.log
+
+start () {
+    if [ -e "$rtdbpidfile" ]; then
+        if is_running "`cat "$rethinkdb_pid_file"`"; then
+            echo "rethinkdb: $instance_name: The instance has already started"
+        else
+            rm "$rethinkdb_pid_file"
+        fi
+    fi
+    echo "rethinkdb: Starting server. (logging to \`$rethinkdb_log_file')"
+    cd /var/lib
+    $rethinkdb_bin --config "$rethinkdb_conf_dir/server.conf" --log-file "$rethinkdb_log_file" --pid-file "$rethinkdb_pid_file" --daemon
+}
+
+stop () {
+    if ! [ -e "$rethinkdb_pid_file" ] ; then
+        echo "rethinkdb: The server is not running (there is no pid file)"
+        exit 1
+    fi
+    rethinkdb_pid="`cat "$rethinkdb_pid_file"`"
+    if is_running "$rethinkdb_pid"; then
+        echo -n "rethinkdb: Waiting for server to stop (pid $rethinkdb_pid) ..."
+        kill -INT "$rethinkdb_pid"
+        while is_running "$rethinkdb_pid"; do
+            echo -n "."
+            sleep 1
+        done
+        echo " Stopped."
+    else
+        rm -f "$rethinkdb_pid"
+    fi
+}
+
+status () {
+    if [ -e "$rethinkdb_pid_file" ] ; then
+        rethinkdb_pid="`cat "$rtdbpidfile"`"
+        if ! is_running "$rethinkdb_pid"; then
+            echo "rethinkdb: stop/crashed"
+        else
+            echo "rethinkdb: start/running, pid `cat "$rtdbpidfile"`"
+        fi
+    else
+        echo "rethinkdb: stop/waiting"
+    fi
+}
+
+case "$0" in
+    start|force-start) start ;;
+    stop|force-stop) stop ;;
+    restart|force-restart) stop; start ;;
+    status) status ;;
+
+    upgrade-config) echo "$0: Nothing to do" ;;
+
+    "") usage_fail ;;
+    *) echo "$0: error: unknown action $1" >&2
+       usage_fail ;;
+esac
+
+else ############## Deprecated pre-2.1 config ##############
+
+itask="${1:-}"
 
 # parse a line from the config file
 conf_read_line () {
@@ -81,17 +155,6 @@ default_cluster_port=29015
 default_http_port=8080
 default_port_offset=0
 
-# is_running <pid>
-# test if the process exists
-is_running () {
-    ps -p "$1" > /dev/null
-}
-
-usage_fail () {
-    echo "Usage: /etc/init.d/rethinkdb [start|stop|restart|force-restart|status]"
-    exit 1
-}
-
 case "$itask" in
     start|stop|restart|force-restart|status)
         true
@@ -106,14 +169,17 @@ case "$itask" in
 esac
 
 # We check for active configurations .
-if ! ls "$rtdbconfigdir"/instances.d/*.conf >/dev/null 2>/dev/null ; then
-    echo "rethinkdb: No instances defined in $rtdbconfigdir/instances.d/"
+if ! ls "$rethinkdb_conf_dir"/instances.d/*.conf >/dev/null 2>/dev/null ; then
+    echo "rethinkdb: No instances defined in $rethinkdb_conf_dir/instances.d/"
     echo "rethinkdb: See http://www.rethinkdb.com/docs/guides/startup/ for more information" ;
     exit
 fi
 
-for rtdbconffile in "$rtdbconfigdir"/instances.d/*.conf ;
+for rtdbconffile in "$rethinkdb_conf_dir"/instances.d/*.conf ;
 do
+
+    echo "rethinkdb: warning: using a deprecated config file '$rtdbconffile'. Run \`$0 upgrade-config' to upgrade." >&2
+
     if ! conf_read "$rtdbconffile" conf; then
         continue
     fi
@@ -217,7 +283,7 @@ do
                 rtdblogfile=$rtdb_directory/log_file
             fi    
             echo "rethinkdb: $instance_name: Starting instance. (logging to \`$rtdblogfile')"
-            "$rtdbbin" --daemon "$@"
+            "$rethinkdb_bin" --daemon "$@"
         fi
     fi
 
@@ -235,3 +301,5 @@ do
         fi
     fi
 done
+
+fi
